/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bc.view;

import bc.BC;
import bc.controller.Drawing_stations_roads;
import bc.controller.Init;
import bc.controller.win_control;
import bc.model.Car;
import bc.model.Maps;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public final class main_win extends javax.swing.JFrame {
    win_control control = new win_control();
    Maps m;
    /**
     * Creates new form main_win
     * @param map
     */
    public main_win(Maps map) {        
        this.m = map;
        this.setTitle("Free-windows simulator");
        initComponents();
        fill_components();
        draw_map();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox6 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jRadioButton8.setText("jRadioButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 810));
        getContentPane().setLayout(null);

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(null);

        jScrollPane3.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(2, 2, 1000, 600);

        jButton4.setText("Skok ďalej");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 630, 100, 60);

        jButton5.setText("Skok nazad");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(309, 630, 100, 60);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/play2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(450, 630, 100, 100);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Čas: ");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(30, 640, 60, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(70, 640, 70, 30);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(30, 662, 110, 10);

        jButton7.setText("Na začiatok");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(190, 630, 100, 60);

        jLabel27.setText("Veľkosti skokov (v sekundách)");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(720, 630, 190, 16);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("0.5");
        jPanel1.add(jRadioButton6);
        jRadioButton6.setBounds(720, 650, 60, 25);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setSelected(true);
        jRadioButton7.setText("1");
        jPanel1.add(jRadioButton7);
        jRadioButton7.setBounds(720, 680, 60, 25);

        buttonGroup2.add(jRadioButton9);
        jRadioButton9.setText("2");
        jPanel1.add(jRadioButton9);
        jRadioButton9.setBounds(800, 650, 60, 25);

        buttonGroup2.add(jRadioButton10);
        jRadioButton10.setText("5");
        jPanel1.add(jRadioButton10);
        jRadioButton10.setBounds(800, 680, 35, 25);

        buttonGroup2.add(jRadioButton11);
        jRadioButton11.setText("10");
        jPanel1.add(jRadioButton11);
        jRadioButton11.setBounds(860, 650, 60, 25);

        jTabbedPane1.addTab("Hlavná obrazovka", jPanel1);

        jPanel2.setLayout(null);

        jLabel1.setText("Vozidlo");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 310, 60, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGV 1", "AGV 2" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(100, 310, 100, 22);

        jLabel2.setText("Scenáre");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 380, 50, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pridanie vozidla");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(730, 100, 170, 17);

        jLabel6.setText("Meno vozidla:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(740, 140, 80, 20);

        jTextField2.setText("AGV3");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(830, 140, 130, 22);

        jLabel7.setText("Začiatočný bod");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(740, 180, 100, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stanica 1", "Stanica 2" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(840, 180, 120, 22);

        jButton1.setText("Pridaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(740, 490, 110, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Odstránenie vozidla");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(730, 550, 160, 17);

        jLabel11.setText("Rýchlosť:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(740, 220, 60, 20);

        jLabel12.setText("Vozidlo:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(740, 586, 46, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGV1", "AGV2" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(800, 590, 110, 20);

        jButton2.setText("Odstráň");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(740, 670, 110, 25);
        jPanel2.add(jLabel13);
        jLabel13.setBounds(80, 340, 50, 20);

        jLabel14.setText("Doba čakania:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(740, 420, 100, 20);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(840, 420, 60, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Pridanie scenára");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(400, 90, 140, 17);

        jLabel17.setText("Vozidlo: ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(400, 130, 60, 20);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(330, 20, 10, 360);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(660, 30, 10, 670);

        jLabel18.setText("Aktuálny bod:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(400, 170, 80, 20);
        jPanel2.add(jLabel19);
        jLabel19.setBounds(490, 170, 70, 20);

        jLabel20.setText("Cieľový bod:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(400, 210, 80, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stanica 1", "Stanica 2", "Stanica 4" }));
        jPanel2.add(jComboBox5);
        jComboBox5.setBounds(480, 210, 110, 22);

        jButton3.setText("Pridaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(400, 330, 110, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Informácie");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 260, 140, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Vozidlá");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(820, 50, 80, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Scenáre");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(450, 40, 100, 30);

        jLabel23.setText("Rýchlosť:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 340, 60, 20);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 400, 630, 270);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGV1", "AGV2" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox6);
        jComboBox6.setBounds(470, 130, 120, 22);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1");
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(810, 220, 40, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2");
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(860, 220, 35, 25);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(910, 220, 35, 25);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4");
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(810, 260, 35, 25);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("6");
        jPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(860, 260, 35, 25);

        jLabel4.setText("Počiatočný čas:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(740, 350, 100, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(840, 350, 60, 22);

        jCheckBox1.setText("Blokujuci");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(740, 450, 79, 25);

        jLabel24.setText("Doba čakania:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(400, 250, 90, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(490, 250, 50, 22);

        jCheckBox2.setText("Blokujuci");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(400, 280, 79, 25);

        jCheckBox3.setText("prvé voľné miesto");
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(840, 380, 140, 25);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(730, 120, 220, 10);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(400, 110, 200, 10);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(730, 570, 240, 10);

        jButton8.setText("Načítať mapu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(30, 90, 200, 50);

        jButton9.setText("Uložiť aktuálnu mapu");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(30, 170, 200, 50);

        jLabel5.setText("Farba");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(740, 310, 50, 16);

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(790, 300, 30, 30);

        jButton10.setText("Výber farby");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(830, 300, 130, 30);

        jLabel9.setText("Aktuálny bod:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(740, 630, 90, 20);
        jPanel2.add(jLabel16);
        jLabel16.setBounds(830, 630, 90, 20);

        jTabbedPane1.addTab("Prehľad", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1024, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Car c = control.selected_vehicle(m, jComboBox1, jLabel13);
        
        jLabel13.setText(Integer.toString(c.getRychlost()));        //update zobrazenia rychlosti vozidla podla comboboxu
        control.fill_plan_info(jTextArea1 ,c, m.getStations());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed

            control.selected_vehicle(m, jComboBox6, jLabel19);      //po akcii v comboboxe sa updatne posledny uzol vozidla
       
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
            control.selected_vehicle(m, jComboBox3, jLabel16);          //po akcii v comboboxe sa updatne posledny uzol vozidla
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             int succ =  control.create_new_car(m, buttonGroup1, jTextField4, jTextField2, jComboBox2, jPanel2, jTextField1, jCheckBox1, jCheckBox3, jTextField5);
            
             if(succ == 1){                                                                     //potvrdenie noveho vozidla
                JOptionPane.showMessageDialog(jPanel2,"Vozidlo upesne vytvorene!");
            }
            else
                JOptionPane.showMessageDialog(jPanel2,"Nebolo mozne vytvorit nove vozidlo");
             
             update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int succ = control.create_new_schedule(m, jComboBox5, jComboBox6, jTextField3, jCheckBox2, jPanel2);    //potvrdenie novej ulohy
        
        if(succ == 1){
            JOptionPane.showMessageDialog(jPanel2,"Vytvaranie ulohy prebehlo upesne!");
            update();
        }
        else if(succ == -1)
            JOptionPane.showMessageDialog(jPanel2,"Nie je miesto pre pohyb vozidla");
        
        else
            JOptionPane.showMessageDialog(jPanel2,"Nebolo mozne vytvorit ulohu pre vozidlo");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            control.dec_time(m, buttonGroup2);          //ubratie z casu
            update_time();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            control.inc_time(m, buttonGroup2);          //pridanie casu
            update_time();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           if(control.isPressed_play() == false){
               control.setPressed_play(true);
               
               Icon pause;
               try {
                   pause = new ImageIcon(new File(BC.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParentFile().toString() + "\\icons\\pause2.png"); //play a pause tlacidlo
                   jButton6.setIcon(pause);
               } catch (URISyntaxException ex) {
                   Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               
               control.play(m, buttonGroup2, jLabel26);
           }
           
           else{
               Icon play;
               try {
                   play = new ImageIcon(new File(BC.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()).getParentFile().toString() + "\\icons\\lay2.png");
                   jButton6.setIcon(play);
               } catch (URISyntaxException ex) {
                   Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               
               control.setPressed_play(false);
            }
           update_time();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        control.setTime(0);
        control.updateCoords(m);        //vynulovanie casu a update na nulovy cas
        update_time();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected()){
           jTextField4.setEnabled(false);       //checkbox pre blokovanie pri vytvarani noveho vozidla
       }
       
       else{
           jTextField4.setEnabled(true);
       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
            jTextField3.setEnabled(false);      //checkbox pre blokovanie pri vytvarani noveho scenara
        else
            jTextField3.setEnabled(true);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser ch = new JFileChooser();   
        int ret;
        try {
            ch.setCurrentDirectory(new File(BC.class.getProtectionDomain().getCodeSource().getLocation().toURI().getPath()));
        } catch (URISyntaxException ex) {
            Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
        }
        ret = ch.showOpenDialog(jButton8);                                              //otvaram subor...najprv sa zobrazi dialog
        if(ret == JFileChooser.APPROVE_OPTION){                                         //ak potvrdim otvaranie
        String subor = ch.getSelectedFile().getPath();                                  //zistim si, ci je to za subor                                              
        
        try {
            Init intial = new Init(subor, m);                                           //a rozbieham vsetko nanovo uz s novou mapou
        } catch (IOException ex) {
            Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        update();
        draw_map();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Color c = JColorChooser.showDialog(this, "Vyberte farbu vozidla", Color.red);   //vyber farby pre vozidlo
        jTextField5.setBackground(c);                                                   //v textfielde som urobil vzorkovnik :D
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        control.delete_car(m, jComboBox3, jPanel2);     //odstranovanie vozidla
        
        update();                                       //updatnem vestky prvky GUI
        draw_map();                                     //a prekreslim zobrazovaci panel
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int saved = 0;
        
        try {
            saved = control.save_map(m, jButton9);                                      //pri ukladani...zistim, aky je vysledok funkcie
        } catch (URISyntaxException ex) {
            Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(saved == 1)                                                                  //ak je uspesne ukladanie
        JOptionPane.showMessageDialog(jPanel2, "Mapa úspešne uložená.");                //informujem message-om
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new main_win(m).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    public void fill_components(){                  //update vsetkych komponentov v programe                                        
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton3.setActionCommand("3");
        jRadioButton4.setActionCommand("4");
        jRadioButton5.setActionCommand("6");
        
        jComboBox6.setModel(control.fill_vehicle_list(m));
        jComboBox1.setModel(control.fill_vehicle_list(m));
        jComboBox3.setModel(control.fill_vehicle_list(m));
        
        
        if(m.getCars().size() > 0)
            jLabel13.setText(Integer.toString(m.getCars().get(0).getRychlost()));
        else
            jLabel13.setText("");
        
        if(jComboBox6.getItemCount() == 0 || jComboBox3.getItemCount() == 0 || jComboBox1.getItemCount() == 0){
            System.out.println("EMPTY VEHICLE LIST");
        }
         
         jComboBox2.setModel(control.fill_station_list(m));
         jComboBox5.setModel(control.fill_station_list(m));
         
         if(jComboBox5.getItemCount() == 0 || jComboBox3.getItemCount() == 0 || jComboBox2.getItemCount() == 0){
            System.out.println("EMPTY STATION LIST");
        }
        jTextField5.setBackground(new Color(255, 0, 0));
        
        if(m.getCars().size() > 0){
            jLabel19.setText(m.getCars().get(0).getLast_node().getID() + " " + m.getCars().get(0).getLast_node().getName());
            jLabel16.setText(m.getCars().get(0).getLast_node().getID() + " " + m.getCars().get(0).getLast_node().getName());
        }
        else{
            jLabel19.setText("");
            jLabel16.setText("");
        }
        
        
        jLabel26.setText(Double.toString(control.getTime()));
        
        if(m.getCars().size() > 0)
            control.fill_plan_info(jTextArea1, m.getCars().get(0), m.getStations());
        else
            jTextArea1.setText("");
        
        jRadioButton3.setSelected(true);
        control.updateCoords(m);
    }
    
    public void draw_map(){
        Drawing_stations_roads sr = new Drawing_stations_roads(m);
        sr.setPreferredSize(jTabbedPane1.getPreferredSize());
        sr.setBackground(Color.white);
        jScrollPane3.setViewportView(sr);
    }
    
    public void update(){
        fill_components();
    }
    
    public void update_time(){
        jLabel26.setText(Double.toString(control.getTime()));
    }
}
